name: onyxsio_grid_view
description: Provides a Flutter grid layout.
version: 1.0.1
# author: Sudesh Bandara
homepage: https://github.com/sudeshnb/onyxsio_grid_view.git
documentation: https://onyxsio.com/

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
